project_id = "ngkhzbzynkhgezkqykeb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
shadow_port = 54320
major_version = 15

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[studio]
port = 54323

[functions]
[functions.ml-sync-v2]
verify_jwt = false

[functions.ml-auth]
verify_jwt = false

[functions.ml-token-renewal]
verify_jwt = false

[functions.ml-webhook]
verify_jwt = false

[functions.ml-security-monitor]
verify_jwt = false
