name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run tests
        run: npm test

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Login to Supabase
        run: supabase login --token "$SUPABASE_ACCESS_TOKEN"

      - name: Push database changes
        run: supabase db push --project-ref "$SUPABASE_PROJECT_REF"

      - name: Deploy functions
        run: supabase functions deploy --project-ref "$SUPABASE_PROJECT_REF" --all
